name       : kfilemetadata
version    : 5.89.0
release    : 69
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.89/kfilemetadata-5.89.0.tar.xz : 658087fd33864e73bee4c78f4da11b3039c4d7e50ac6fc0a68ed56199bf64b11
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : programming.library
summary    : Simple library for extracting the text and metadata
description: |
    Simple library for extracting the text and metadata.
optimize   : lto
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(libattr)
    - pkgconfig(libavformat)
    - pkgconfig(poppler-qt5)
    - pkgconfig(taglib)
    - ebook-tools-devel
    - karchive-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kconfig-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
