name       : kfilemetadata
version    : 5.71.0
release    : 51
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.71/kfilemetadata-5.71.0.tar.xz : 2e302958065157c1f9ea4a189bbca40b7dbed019767a3380e34e0b6a633c75fe
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Simple library for extracting the text and metadata
description: |
    Simple library for extracting the text and metadata.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(exiv2)
    - pkgconfig(libattr)
    - pkgconfig(libavformat)
    - pkgconfig(libcurl)
    - pkgconfig(libssh)
    - pkgconfig(poppler-qt5)
    - pkgconfig(taglib)
    - ebook-tools-devel
    - extra-cmake-modules
    - karchive-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kconfig-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
