name       : kfilemetadata
version    : 5.74.0
release    : 53
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/kfilemetadata-5.74.0.tar.xz : c5fab0101a39265eeb1884522ed548ae106cd434d6313be1fc0bdba4f29dc5a8
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Simple library for extracting the text and metadata
description: |
    Simple library for extracting the text and metadata.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(exiv2)
    - pkgconfig(libattr)
    - pkgconfig(libavformat)
    - pkgconfig(libcurl)
    - pkgconfig(libssh)
    - pkgconfig(poppler-qt5)
    - pkgconfig(taglib)
    - ebook-tools-devel
    - extra-cmake-modules
    - karchive-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kconfig-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
