name       : kfilemetadata
version    : 5.66.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.66/kfilemetadata-5.66.0.tar.xz : d78c2128887591229e6c61c60e77af8647e407d570b07892f5f06ab682f807b9
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Simple library for extracting the text and metadata
description: |
    Simple library for extracting the text and metadata.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(exiv2)
    - pkgconfig(libattr)
    - pkgconfig(libavformat)
    - pkgconfig(libcurl)
    - pkgconfig(libssh)
    - pkgconfig(poppler-qt5)
    - pkgconfig(taglib)
    - ebook-tools-devel
    - extra-cmake-modules
    - karchive-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kconfig-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
