name       : kfilemetadata
version    : 5.70.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.70/kfilemetadata-5.70.0.tar.xz : 52ff64e19bbbf68cae4ec98ecc0d7da218ddf501edf71c58502081535051c1a2
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Simple library for extracting the text and metadata
description: |
    Simple library for extracting the text and metadata.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(exiv2)
    - pkgconfig(libattr)
    - pkgconfig(libavformat)
    - pkgconfig(libcurl)
    - pkgconfig(libssh)
    - pkgconfig(poppler-qt5)
    - pkgconfig(taglib)
    - ebook-tools-devel
    - extra-cmake-modules
    - karchive-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kconfig-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
