name       : kfilemetadata
version    : 5.94.0
release    : 74
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.94/kfilemetadata-5.94.0.tar.xz : 7f573b1a30349e331309dcf9e3374d7a304b6bdd0453a122366f7bd2574977e6
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : programming.library
summary    : Simple library for extracting the text and metadata
description: |
    Simple library for extracting the text and metadata.
optimize   : lto
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(libattr)
    - pkgconfig(libavformat)
    - pkgconfig(poppler-qt5)
    - pkgconfig(taglib)
    - ebook-tools-devel
    - karchive-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kconfig-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
