name       : kfilemetadata
version    : 5.38.0
release    : 11
source     :
    - https://download.kde.org/stable/frameworks/5.38/kfilemetadata-5.38.0.tar.xz : 95ce8b047895d4b1efd34e841035147e282f03996e1d33d79f09a6d469ca25a0
license    :
    - LGPL-2.0
    - LGPL-2.1
    - LGPL-3.0
component  : programming
summary    : Simple library for extracting the text and metadata.
description: |
    Simple library for extracting the text and metadata.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(libavformat)
    - pkgconfig(poppler-qt5)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(taglib)
    - attr-devel
    - ebook-tools-devel
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
