name       : kfilemetadata
version    : 5.35.0
release    : 9
source     :
    - https://download.kde.org/stable/frameworks/5.35/kfilemetadata-5.35.0.tar.xz : 8e7c0e93469edd66bcc45db90c6116fd342796cbd70492eb3eac836d20b06a2a
license    :
    - LGPL-2.0
    - LGPL-2.1
    - LGPL-3.0
component  : programming
summary    : Simple library for extracting the text and metadata.
description: |
    Simple library for extracting the text and metadata.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(libavformat)
    - pkgconfig(poppler-qt5)
    - pkgconfig(Qt5Core)
    - pkgconfig(taglib)
    - attr-devel
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
