name       : kfilemetadata
version    : 5.39.0
release    : 14
source     :
    - https://download.kde.org/stable/frameworks/5.39/kfilemetadata-5.39.0.tar.xz : 0feadb5850557be4d372dcf792c83176276616fc839965c23ed87b7525bc9dd5
license    :
    - LGPL-2.0
    - LGPL-2.1
    - LGPL-3.0
component  : programming
summary    : Simple library for extracting the text and metadata.
description: |
    Simple library for extracting the text and metadata.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(libavformat)
    - pkgconfig(libcurl)
    - pkgconfig(libssh)
    - pkgconfig(poppler-qt5)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(taglib)
    - attr-devel
    - ebook-tools-devel
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
