name       : kfilemetadata
version    : 5.59.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.59/kfilemetadata-5.59.0.tar.xz : 7aeacfc538375dae4c8b3ab6411216a48a6971f012f1ab1b9d1e0f835429d6c9
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Simple library for extracting the text and metadata
description: |
    Simple library for extracting the text and metadata.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(exiv2)
    - pkgconfig(libattr)
    - pkgconfig(libavformat)
    - pkgconfig(libcurl)
    - pkgconfig(libssh)
    - pkgconfig(poppler-qt5)
    - pkgconfig(taglib)
    - ebook-tools-devel
    - extra-cmake-modules
    - karchive-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kconfig-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
