name       : kfilemetadata
version    : 5.82.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.82/kfilemetadata-5.82.0.tar.xz : a5625e00e91ffcbe34a8bd38c8af9339784a596a2ae844ded5250b3c213ceab8
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : programming.library
summary    : Simple library for extracting the text and metadata
description: |
    Simple library for extracting the text and metadata.
optimize   : lto
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(libattr)
    - pkgconfig(libavformat)
    - pkgconfig(poppler-qt5)
    - pkgconfig(taglib)
    - ebook-tools-devel
    - karchive-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kconfig-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
