name       : kfilemetadata
version    : 5.81.0
release    : 62
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.81/kfilemetadata-5.81.0.tar.xz : 318cd48f2b2400b2e453a4c3f373e84dc1296c972c0b0e01c5c39429353d6a31
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : programming.library
summary    : Simple library for extracting the text and metadata
description: |
    Simple library for extracting the text and metadata.
optimize   : lto
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(libattr)
    - pkgconfig(libavformat)
    - pkgconfig(poppler-qt5)
    - pkgconfig(taglib)
    - ebook-tools-devel
    - karchive-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kconfig-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
