name       : kfilemetadata
version    : 5.32.0
release    : 8
source     :
    - http://download.kde.org/stable/frameworks/5.32/kfilemetadata-5.32.0.tar.xz : 0e817ff8d63de773b4e320e4864936bb724cd80e04ad38c2035dd19eeb0ba905
license    :
    - LGPL-2.0
    - LGPL-2.1
    - LGPL-3.0
component  : programming
summary    : Simple library for extracting the text and metadata.
description: |
    Simple library for extracting the text and metadata.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(libavformat)
    - pkgconfig(poppler-qt5)
    - pkgconfig(Qt5Core)
    - pkgconfig(taglib)
    - attr-devel
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
