name       : kfilemetadata
version    : 5.36.0
release    : 10
source     :
    - https://download.kde.org/stable/frameworks/5.36/kfilemetadata-5.36.0.tar.xz : 750c1f408bad265ee10bfcd60eab88988d8bb6b3b38fd59ebad1899c683b269d
license    :
    - LGPL-2.0
    - LGPL-2.1
    - LGPL-3.0
component  : programming
summary    : Simple library for extracting the text and metadata.
description: |
    Simple library for extracting the text and metadata.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(libavformat)
    - pkgconfig(poppler-qt5)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(taglib)
    - attr-devel
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
