name       : kfilemetadata
version    : 5.28.0
release    : 6
source     :
    - http://download.kde.org/stable/frameworks/5.28/kfilemetadata-5.28.0.tar.xz : 86fbcf1aa89d7224a99608aeb5cb3d912afe126e14a91c5d571060ec7f77b16b
license    :
    - LGPL-2.0
    - LGPL-2.1
    - LGPL-3.0
component  : programming
summary    : Simple library for extracting the text and metadata.
description: |
    Simple library for extracting the text and metadata.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(libavformat)
    - pkgconfig(poppler-qt5)
    - pkgconfig(Qt5Core)
    - pkgconfig(taglib)
    - attr-devel
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
