name       : kfilemetadata
version    : 5.25.0
release    : 3
source     :
    - http://download.kde.org/stable/frameworks/5.25/kfilemetadata-5.25.0.tar.xz : f7f7ede8b3a7a518e8058374733847c2610b59aa717562c253f70a01c614ebf9
license    :
    - LGPL-2.0
    - LGPL-2.1
    - LGPL-3.0
component  : programming
summary    : Simple library for extracting the text and metadata.
description: |
    Simple library for extracting the text and metadata.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(libavformat)
    - pkgconfig(poppler-qt5)
    - pkgconfig(Qt5Core)
    - pkgconfig(taglib)
    - attr-devel
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
