name       : kfilemetadata
version    : 5.92.0
release    : 72
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.92/kfilemetadata-5.92.0.tar.xz : d624d3551094cf73d802b6e95bcd78577ce9eb1e9cbb9a8f340dcad066ea15ce
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : programming.library
summary    : Simple library for extracting the text and metadata
description: |
    Simple library for extracting the text and metadata.
optimize   : lto
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(libattr)
    - pkgconfig(libavformat)
    - pkgconfig(poppler-qt5)
    - pkgconfig(taglib)
    - ebook-tools-devel
    - karchive-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kconfig-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
