name       : kfilemetadata
version    : 5.50.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/kfilemetadata-5.50.0.tar.xz : f414e10bfb3d5f3cec14a7074bfb493d6621dbf73c36fcdca7f765bb3a226118
license    :
    - LGPL-2.0
    - LGPL-2.1
    - LGPL-3.0
component  : programming
optimize   : lto
summary    : Simple library for extracting the text and metadata.
description: |
    Simple library for extracting the text and metadata.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(libavformat)
    - pkgconfig(libcurl)
    - pkgconfig(libssh)
    - pkgconfig(poppler-qt5)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(taglib)
    - attr-devel
    - ebook-tools-devel
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
